### ISSUE TITLE
Endpoint for impacted programme

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#101]
We need an endpoint to which a user can submit data related to an impacted programme

The data should contain the following:
- incident_id: numerical id 
- country: numerical id
- scope: numerical id, needs static data
- area: numerical id 
- start_date: date
- end_date: date
- impact_type: numerical id 
- agency: numerical id
- programme_type: numerical id, needs static data
- description: string
- submitted_by: numerical id
- last_modified_by: numerical id
- last_modified_date: date
- submitted_date: date

mandatory fields should be impact_type, agency and incident_id

**Comment by daniel-tabarcea** [comment]
![programme1](https://user-images.githubusercontent.com/17467562/45220681-9ac28a00-b2b7-11e8-8cbb-4c50ca50289f.png)
![programme2](https://user-images.githubusercontent.com/17467562/45220682-9ac28a00-b2b7-11e8-823f-f63bf8445bd0.png)
![programme3](https://user-images.githubusercontent.com/17467562/45220684-9ac28a00-b2b7-11e8-9d35-505eac529847.png)

**Comment by daniel-tabarcea** [comment]
Since Area Impacted seems to be quite cumbersome as a dropdown, i'm thinking we just leave it as a plain text input. @drzackyll  what are your thoughts on this? 
In ssirs if the scope is a city it lets you select a city, if the scope if country it lets you select just the current country, if the scope is security level area there was nothing to choose from.

**Comment by drzackyll** [comment]
@daniel-tabarcea could we not populate that dropdown with whatever api we'll use for selecting cities elsewhere (if it's city level) and other wise do as SSIRS does (current country if country selected) and nothing for security level area?

**Comment by daniel-tabarcea** [comment]
We can do that, we can make like it is in SSIR with not much effort. My questioning is more about whether it would be good user experience or not

**Comment by drzackyll** [comment]
I'll ask the business folks if they have a strong feeling about this and get back to you.

**Comment by reinbach** [comment]
Endpoint is;
`/api/incident_programmes/`

editable fields 
```
{
            "incident_id",
            "impact",
            "country",
            "scope",
            "area",
            "start_date",
            "end_date",
            "agency",
            "programme_type",
            "description",
}
```

Relevant static data endpoints;
- `/api/programme_types/`
- `/api/scope/`
- `/api/area/`
