### ISSUE TITLE
Updates to exported data

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#102]
Exported incidents should include data related to impacts

**Comment by daniel-tabarcea** [comment]
This is a sample from SSIRS
[Incident details.pdf](https://github.com/unicef/sir-releases/files/2361315/Incident.details.pdf)

**Comment by drzackyll** [comment]
@reinbach @daniel-tabarcea business owners would also like uploaded files to be included in export. is this possible?

**Comment by reinbach** [comment]
@drzackyll how exactly would they like the uploaded files to be part of the export? If they export in XLS format, but the file uploaded is an PDF? 

Are they wanting the links to the files to show up in the export?

**Comment by drzackyll** [comment]
@reinbach I suspected their idea wouldn't be implementable. I'm asking if a field with a link is an acceptable alternative. Will let you know.

**Comment by drzackyll** [comment]
a link is acceptable

**Comment by saxix** [comment]
@drzackyll / @daniel-tabarcea  About `impacts` in exported data, which data should be added ?
We have different values depend on Premise/Property/Person/Programme
