### ISSUE TITLE
Some data visible when not logged in

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#105]
I had SIR running locally and navigated to localhost 8080 and it asked me for username and password. But I could also see some dashboard data behind the login popup.

**Comment by drzackyll** [comment]
<img width="1271" alt="screen shot 2018-09-11 at 10 10 12 am" src="https://user-images.githubusercontent.com/8411545/45365767-436c3480-b5ab-11e8-8567-79943afaae49.png">

**Comment by daniel-tabarcea** [comment]
related to #129

**Comment by adi130987** [comment]
This login popup belongs to the BE side and it's triggered by the first request(fired without jwt token).
The login page is ready and no request will be triggered until login with ms account is made. If the user is not logged in it will be redirected to FE login page. See #151 
Closing issue...
