### ISSUE TITLE
Add crash type sub-categories to new incident form

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#108]
If someone selects accident, when they select the crash type, there should be an additional field for selecting a crash type subcategory. See screenshots.

**Comment by drzackyll** [comment]
<img width="497" alt="screen shot 2018-09-12 at 8 38 46 am" src="https://user-images.githubusercontent.com/8411545/45425484-7ecc3900-b667-11e8-96d6-0cded733e81c.png">
<img width="975" alt="screen shot 2018-09-12 at 8 38 33 am" src="https://user-images.githubusercontent.com/8411545/45425486-7ecc3900-b667-11e8-9c69-1fe636fc83ae.png">

**Comment by saxix** [comment]
Is it always mandatory ?

**Comment by drzackyll** [comment]
Yes, it should be mandatory

**Comment by saxix** [comment]
new endpoints added: 

**Crash Types**:
`/api/crash_types/`
`/api/crash_types/?serializer=nested` embed sub-types in response

**Crash SubTypes**:
`/api/crash_subtypes/`

**Incident**
`api/incidents/?serializer=nested`

**Note**
- CrashSubType is mandatory only if CrashType is set
- Incident `crash_sub_type` is ALWAYS stored as text. When selected from `CrashSubType` list it should be passed as text. This to maintain consistency with "_Other_" and keep the protocol with the front-end simple. No ForeignKey exists between Incident and `CrashSubType`. It is possible to create foreign key if needed, but some more complexity need to be added.

**Comment by drzackyll** [comment]
@saxix thanks for this. would you be able to capitalize each of the subtypes? and the subcategories for child and adult should be separated (currently it's `childadult`, but it should be two separate subcategories).
