### ISSUE TITLE
On impact page, edit personnel action doesn't work

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#114]
If you add personnel to the impact list then click to edit, it takes you to a blank "Impacted UN Personnel" page.

**Comment by drzackyll** [comment]
<img width="1023" alt="screen shot 2018-09-25 at 10 05 00 am" src="https://user-images.githubusercontent.com/8411545/46019664-9d402480-c0aa-11e8-9fa9-8c07dfa5f56d.png">
<img width="1184" alt="screen shot 2018-09-25 at 10 05 21 am" src="https://user-images.githubusercontent.com/8411545/46019670-a0d3ab80-c0aa-11e8-9d8d-dea43594d19f.png">

**Comment by drzackyll** [comment]
See URL in second screenshot (after edit button is clicked)

**Comment by drzackyll** [comment]
* this is the same for non-un personnel

**Comment by acory** [comment]
Backend needs to return the id of the items in the list

**Comment by daniel-tabarcea** [comment]
This has been fixed in the meantime, the lastest version of the API do not have this issue
