### ISSUE TITLE
Automatic email/on-screen notification triggering

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#117]
We need to make sure that the proper people are notified via email and on-screen when an incident needs their attention. This means if a Security Adviser submits an incident, the Regional folks should be notified. If a Regional Security Adviser sends the incident back for more information, the Security Adviser should be notified. If the RSA approves, the incident should be sent to HQ (and those people should be notified), then the reviewers (legal, DFAM, etc.). This should all be somewhat automated based upon the user's particular role.

**Comment by drzackyll** [comment]
Is it possible to set up some kind of warning if there is a problem with the email system? If emails get bounced back or whatever? Business folks keep asking about it.

**Comment by reinbach** [comment]
@drzackyll So it looks like we are going to be relying on errors notifications via Sentry

**Comment by drzackyll** [comment]
ok sounds good. i'll pass it along!
