### ISSUE TITLE
Create separate Log In page

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#129]
The business folks have requested a login page, rather than a dialog box that appears over the dashboard.

**Comment by daniel-tabarcea** [comment]
We should implement a more robust authentication system first, the one we have right now was only meant as a stop gap measure. I'm waiting on answers from Rob at the moment to figure out what we need on the front-end as the back-end i think is ready

**Comment by drzackyll** [comment]
Ok sounds good. In that case maybe this card is related to #105

**Comment by daniel-tabarcea** [comment]
Yes, we need to put everything behind the login page

**Comment by adi130987** [comment]
This is done in #151. No data will be available to user if it's not logged in.
