### ISSUE TITLE
Add case number to events and incidents

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#130]
Case Number should be automatically generated when an incident or event is added.

**Comment by daniel-tabarcea** [comment]
@drzackyll  I can't find anything on the format for the case number, can you check old emails and see what business said about it?

**Comment by drzackyll** [comment]
They have no strong preference as long as they're unique. Perhaps sequential 6 digit numbers starting with E or I if it's an event or incident? Do you have any ideas?

**Comment by drzackyll** [comment]
@reinbach this will be created on the BE right?

**Comment by reinbach** [comment]
@drzackyll It should be, not happening right now. I missed this somehow. I'll get this sorted out now.

**Comment by drzackyll** [comment]
@reinbach ok. not the highest priority, if you have other items that need your attention.

**Comment by reinbach** [comment]
Should be all set now
