### ISSUE TITLE
Lat, Long validation issue

### ISSUE THREAD

**Issue by acory** [unicef/sir-releases#131]

**Comment by acory** [comment]
Enter value in Latitute, Longitude fields then delete the values . Save .

![validation.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2653445c9c41a006b48cd/125516c66e82c728ace21e0d46fe95962a8682bd86e6b101e81fe086264c22703d46f9692587bb7eb91b2f595e5a4bad48515f44fdab812ca6e23a24984019af80330b2b9b645bf9fa9015ad03bb2a8a4a86beb98c4fc4e03522e58b9d02.png)

**Comment by adi130987** [comment]
@reinbach regarding `latitude` and `longitude` fields on incident, there is a validation on BE: once a valid value was saved it will not accept anything else then numbers. For example if a user enters the wrong latitude&longitude, saves and the right values for these fields are still unknown, the user will not be able to clear these fields. Should we address this issue?

**Comment by reinbach** [comment]
@adi130987 I'll take a look at that, yes I should be address this issue.

**Comment by reinbach** [comment]
@adi130987 Looks like you need to set the `latitude`/`longitude` values to `null` to clear them

**Comment by adi130987** [comment]
@reinbach ok. I'll make an update for this. Thx.
