### ISSUE TITLE
Create different roles for admins

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#132]
As mentioned by @saxix, create an admin role for non-technical users. Should prohibit changing anything that might cause breakage.

**Comment by drzackyll** [comment]
@reinbach looking at the admin panel i'm a little unsure what permissions we should grant to the couple of admins who will be adding or deleting categories, subcategories, etc. I understand there are some permissions that should not be granted to non-technical folks for fear that they could break something. Would it be possible to either have a group that has the proper edit permissions or simply a list of which individual permissions to grant from the User Permissions section of user's profile?

**Comment by reinbach** [comment]
You can just set the user to `is staff` that will provide them with admin access, and be able to change the relevant admin sections. There is always going to be an issue around granted to much ability to users, who mistakenly modify data.
