### ISSUE TITLE
Solutions for 'installable app' or homescreen shortcut for mobile

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#133]
Creating this card so the task is written down

**Comment by drzackyll** [comment]
Further testing in progress

**Comment by daniel-tabarcea** [comment]
![sample ios](https://user-images.githubusercontent.com/17467562/47794408-11fd2300-dd29-11e8-8656-040676f60874.png)
This is what the prompt looks like at the moment. Is this enough or is something else needed?

**Comment by drzackyll** [comment]
I think that's good!
