### ISSUE TITLE
Add link to admin panel on side menu

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#134]

**Comment by adi130987** [comment]
For now the link was added as last option and it will open admin panel in a new tab.
![Screenshot from 2018-10-08 16-30-01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58c6b01a3ac2041a00a63991/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f27b3dd5bb68ee1436525f424ead53444d04bea6d37ef5f22e7a985959e5d73b5670ce3c14a9b98b16bf01bb72834885e2bade5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5bff4be14852a1173166e4647b.png)

**Comment by drzackyll** [comment]
@adi130987 Ok sounds good. Thanks!
