### ISSUE TITLE
Remove default date in datepicker

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#135]
Datepicker has Wed Dec 31 1969 by default

**Comment by drzackyll** [comment]
<img width="1025" alt="screen shot 2018-10-03 at 4 02 31 pm" src="https://user-images.githubusercontent.com/8411545/46436022-e6851980-c725-11e8-989c-8417ff01d507.png">

**Comment by adi130987** [comment]
@drzackyll I do not think this is a valid issue anymore. Datepicker fields were updated using a new component. 

I cannot reproduce the issue.
