### ISSUE TITLE
Update references between country region and city

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#139]
This is the regarding the relationship between countries, regions and cities in the API.
/api/cities 
/api/regions
/api/countries 

There is no way at the moment to know what the relationship between regions and countries is, and what the relationship between cities and regions is. 

So i think each region should have the id of the country it belongs to, and each city should have the id of the region it belongs to. Also having the id of the country in cities would be nice, but is optional.

**Comment by daniel-tabarcea** [comment]
So a country would look like
```
    {
        "id": 3,
        "name": "Spain",
        "business_area_code": ""
    }
```
A region would look like 
```
    {
        "id": 8,
        "name": "Catalonia",
        "country": 3
    }
```
and a city would look like 
```
    {
        "id": 4,
        "name": "Barcelona",
        "region": 8,
        "country": 3  // optional, only if it's not much effort to keep it 
    }
```

**Comment by reinbach** [comment]
My understanding is that countries are within a region. So `region`is showing up with the country endpoints. Will look into adding the `region` to cities endpoint as well then.
