### ISSUE TITLE
Workflows and notifications

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#140]
The general flow of things is as follows:

The group called 'Country Field Security Advisers' will be the ones inputting data into the forms initially. They can save, submit, or print the data.

If they submit, both 'Regional Security Advisers' and 'HQ Security Team' are notified in their application and via email. The submitted SIR will appear in their workspace when they log in.

HQ and RSA will review the report and have two options: send the report back to the Country Field Security Adviser for refinement (they will say in comments how it should be refined) or approve the report. The Country Field Security Adviser should receive notification in either case.

HQ will then transfer the SIR to one or more of the 'commenter' group. Not all SIRs will go to all members of the commenter group.

**Comment by drzackyll** [comment]
connects to #117

**Comment by daniel-tabarcea** [comment]
I'm guessing this is just for incidents and not events, right? If it's the case are events visible to everyone at all times? 
At which point does the report stop being visible to the CFSA that submitted the report?

**Comment by drzackyll** [comment]
I've asked for more information about whether the HQ group should have the ability to select particular types of 'commenters' to review an SIR (eg. send it to the legal team, but not to DFAM). Will update.

**Comment by drzackyll** [comment]
@daniel-tabarcea I believe only incidents go through the submission process. I think events will likely be visible by everyone. I would think that perhaps the report might stay visible in perpetuity for the CFSA that created it.

**Comment by drzackyll** [comment]
here's an update to the above from an email a just received:

`The Regional Security Advisers and the HQ Security Team can review the incident simultaneously.  EOD, DHR, Legal, Staff Wellbeing and DFAM (reviewer groups) will only receive a notification once the HQ Security Team has reviewed the SIR.
 
For gender-based security incidents, the HQ Security Team will only send it to Staff Wellbeing and Legal as required.  The HQ Security Team should be able to send a SIR to specific reviewer groups.`

**Comment by reinbach** [comment]
Notification sent to users in The Regional Security Advisers and the HQ Security Team, on submitted.

The Regional Security Advisers and the HQ Security Team can "reject" an incident at `/api/incident/<incident-id>/rejected/`, does require a comment on the incident, otherwise 409 response. Notification sent to `submitted_by` on rejection of incident.

Able to send alert to relevant alert group with endpoint;
`/api/incident/<incident_id>/alert/<alert_group_id>/`

or to all alert groups associated with incident;
`/api/incident/<incident_id>/alert/`
