### ISSUE TITLE
Add endpoints for Send Back and Approve

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#143]
Related to #140. 
Endpoints are needed for approve and send back actions, similar to `/api/incidents/<incident id>/submit/`.
The send back action should accept a comment as a mandatory field.

**Comment by reinbach** [comment]
`/api/incidents/<incident_id>/approve/`
and 
`/api/incidents/<incident_id>/reject/` <- requires comment on incident
endpoints are available.

See #140 for more details

**Comment by daniel-tabarcea** [comment]
`/api/incidents/<incident_id>/reject/`  throws a 404 error with PUT

**Comment by reinbach** [comment]
Not having this issue, can you double check the `incident_id` being used in the url and ensure user is in `Regional Security Advisers`, and `HQ Security Team`.

May need to re-run the `make init` to ensure permissions updated/set correctly for those groups.

**Comment by drzackyll** [comment]
@daniel-tabarcea @reinbach is this sorted out?

**Comment by daniel-tabarcea** [comment]
This has been sorted out
