### ISSUE TITLE
Impacted programme Area issue

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#147]
The API for impacted programmes (`/api/incident_programmes/`) returns 400 when trying to add an area.

```Invalid pk \"1\" - object does not exist.```

Area can be a city, a country or some other value and in this case I tried adding a city. 

If it's too complex to validate based on what scope was selected, it's better to disable validations for Area

**Comment by reinbach** [comment]
Currently area is related to `/api/area/` endpoints which are records that can be associated with a country. Has `name` and `country` fields.

`country` is already a field on `incident_programmes`, so `area` should probably not accept country as an option. I'm not sure how Area is going to managed. If we're just going to accept cities then we can change `area` to reference`cities` instead?

**Comment by daniel-tabarcea** [comment]
@drzackyll  Can we get more info on this?

**Comment by drzackyll** [comment]
relates to #226

**Comment by drzackyll** [comment]
see recent comments on #226 for more info

**Comment by reinbach** [comment]
@daniel-tabarcea I'm not sure if there is anything I should be doing for this issue. I've made some changes as per #226. Let me know if I do need to do something else.

**Comment by daniel-tabarcea** [comment]
Since Area is now a plain text field (#226) we can consider this issue resolved
