### ISSUE TITLE
Some fields not populating when staff member chosen on impacts

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#152]
On Impacts, when I click to add impacted UN personnel, then select a user to auto populate the fields, only first and last name populate.

**Comment by daniel-tabarcea** [comment]
This is an issue related to how users are entered in the system, it's an issue with the mock data we're using

**Comment by drzackyll** [comment]
@daniel-tabarcea ok so this issue can be closed?

**Comment by daniel-tabarcea** [comment]
Yes, it is not an issue from our side

**Comment by drzackyll** [comment]
cool thanks
