### ISSUE TITLE
Can all exported values be words?

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#154]
On exporting incidents, there are some columns that export a numerical ID value instead of the label, which would surely be more helpful for the folks using this. Is there any way to make these fields display the actual word values? Screenshots included.

**Comment by drzackyll** [comment]
<img width="129" alt="screen shot 2018-10-09 at 3 52 19 pm" src="https://user-images.githubusercontent.com/8411545/46694879-f4caae00-cbdb-11e8-8fda-974072fcc018.png">
<img width="649" alt="screen shot 2018-10-09 at 3 52 08 pm" src="https://user-images.githubusercontent.com/8411545/46694880-f4caae00-cbdb-11e8-9809-47cac7283f4f.png">

**Comment by drzackyll** [comment]
As you can see, it would be more helpful for Region to list "North America" rather than "1". And it would be more helpful for the actual incident categories, countries, cities, etc. to have the word values listed.

**Comment by drzackyll** [comment]
@reinbach exports look pretty good; the only issue i see is that region and city are still numbers
![Screen Shot 2018-10-16 at 9.23.23 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a371f110284f5d5c5edd3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19141c95df542e74453a7163162ee732431.png)

**Comment by reinbach** [comment]
@drzackyll Region and city are free form fields. I think Region needs to be changed to a foreign key (See #164) so that needs to be corrected. But I think city is correct, did `1` get entered for City?

**Comment by daniel-tabarcea** [comment]
From the front-end at the moment we are sending cities as numbers since it is a dropdown. We will change that to a plain text input

**Comment by reinbach** [comment]
@daniel-tabarcea actually can you continue to do that, and I fix the backend to handle that properly. Not sure why we have free form text field on the backend for cities and regions

**Comment by reinbach** [comment]
@drzackyll Region has been fixed, will show value now. City has been left alone, as we expect the city value provided to be the name, so that will show in the export correctly, once frontend and backend are in sync.
