### ISSUE TITLE
Add profile API

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#156]
We need an endpoint which the user calls, like `/api/profile`  where the user can get information about name, roles, and other relevant information. 

It is planned for the user to be able to edit his profile but provisions for that are not required right now.

**Comment by reinbach** [comment]
The `/api/users/` endpoint has the user information, added `roles` and `teams` to the resulting dataset. Not sure if we're using teams much at the moment.

**Comment by daniel-tabarcea** [comment]
Yes, but as i user i don't know what my id is when i'm logged in so i don't know of all the users which is me

**Comment by reinbach** [comment]
Ah sorry, I misunderstood the request. 
I've gone and created the necessary `/api/profile/` endpoint.

**Comment by daniel-tabarcea** [comment]
`/api/profile` works but `/api/profile/` doesn't

**Comment by drzackyll** [comment]
@daniel-tabarcea can this card be moved to `Done`?

**Comment by daniel-tabarcea** [comment]
Yes, profile endpoint works as expected
