### ISSUE TITLE
Change 'City' field to text input instead of dropdown

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#160]
There's some concern that we won't have all the possible cities available

**Comment by reinbach** [comment]
backend is expecting/setup for cities as being text input

**Comment by daniel-tabarcea** [comment]
@drzackyll is this just for incidents or for impacts also?

**Comment by drzackyll** [comment]
I’d say for impacts as well

**Comment by adi130987** [comment]
we need to make sure filtering on incidents list works and city is displayed as needed

**Comment by daniel-tabarcea** [comment]
These endpoints still require cities as ids: 
`/api/incident_premises/`
`/api/incident_evacuations/`
`/api/incident_involved/`

**Comment by reinbach** [comment]
The endoints above now expect text for cities
