### ISSUE TITLE
Allow groups to be subset for region

### ISSUE THREAD

**Issue by reinbach** [unicef/sir-releases#164]
Restrict "Regional Security Advisers" to a specific region and notify only those in the same region as the submitted incident region

**Comment by reinbach** [comment]
@drzackyll So I just realized that we have the region field set on the Incident to an char field. I think we need to change that to a drop down list, if we want to tie a Region Advisor group of users to a specific region. Otherwise Region entered may not match up correctly.

**Comment by drzackyll** [comment]
@reinbach Ok sounds good. Will that slow anything down for us?

**Comment by reinbach** [comment]
@drzackyll will probably require an update in the frontend to handle the region as a dropdown

**Comment by reinbach** [comment]
@drzackyll Looks like the frontend is already handling regions as a dropdown in the frontend, so I get this resolved.

**Comment by drzackyll** [comment]
@reinbach ok sounds good
