### ISSUE TITLE
Collapse filter panel by default on mobile on Events List and Incidents List

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#167]
They think the panels take up too much space on mobile

**Comment by drzackyll** [comment]
<img width="322" alt="screen shot 2018-10-11 at 3 15 08 pm" src="https://user-images.githubusercontent.com/8411545/46828138-7c452800-cd68-11e8-99b4-4cb7ee6f297f.png">
<img width="338" alt="screen shot 2018-10-11 at 3 14 50 pm" src="https://user-images.githubusercontent.com/8411545/46828139-7c452800-cd68-11e8-87f4-84f97bf12d05.png">

**Comment by adi130987** [comment]
We should improve filters collapse/expand btn design/place. It should only show on resolutions lower than 1024px.
