### ISSUE TITLE
Auto-complete is duplicating people

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#184]
The auto-complete function seems to be duplicating the person each time I use it.

**Comment by drzackyll** [comment]
<img width="996" alt="screen shot 2018-10-16 at 3 50 49 pm" src="https://user-images.githubusercontent.com/8411545/47043391-834eaa80-d15b-11e8-86c2-377e6915cc1e.png">

**Comment by acory** [comment]
@reinbach BK issue. I tried populating person.id with the id of the selected user but it 's still duplicating the user

**Comment by drzackyll** [comment]
relates to #236

**Comment by reinbach** [comment]
@drzackyll I'm not able to reproduce this issue locally.
- I added a person in UNICEF Personnel impact section, they did not get duplicated
- I added a person in Non-UNICEF Personnel impact section, they do no show up in dropdown.

Not sure if I'm missing something, can you provide more details, if still seeing this issue.

**Comment by drzackyll** [comment]
@reinbach after a quick check, it may not be an issue anymore? will keep an eye on it but move this one to closed.
