### ISSUE TITLE
Export bugs

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#185]
It looks like after filtering by keyword or by country, the exported files are not filtered.

**Comment by drzackyll** [comment]
@daniel-tabarcea there's also the option to filter by synced vs not synced. but there is no way to export not synced records right? bc they're kept on the front end.

**Comment by reinbach** [comment]
@drzackyll locally the filtering by country and exporting is working for me. What keyword/country are you using? Can you send me a sample of the URLs you're using

**Comment by drzackyll** [comment]
@reinbach here's a screenshot of the screen before exporting
![Screen Shot 2018-10-17 at 3.32.46 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f46b7191a37bf111294f5b595ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e94d51a31b306bee772431.png)

**Comment by drzackyll** [comment]
then the URL for the export doesn't have country: `http://localhost:8080/api/incidents/?format=pdf`

**Comment by drzackyll** [comment]
so perhaps a FE issue

**Comment by reinbach** [comment]
yeah looks like it may be a FE issue

**Comment by adi130987** [comment]
Issues described above are fixed, but the generated export file has issues.

Ex 1(PDF): I only have 2 incidents and one has multiple attachments
![Screenshot from 2018-10-24 10-35-15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58c6b01a3ac2041a00a63991/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f27b3dd7b768ee1236525a424fa953444d04bea6d37ef5f22e7a985959e5d73b5670ce3c14a9b98b16bf01bb72834885e2bade5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5cf648e74b50a0113064ee647b.png)

Ex 2 (CSV): Involved column has duplicated data or missing data
![Screenshot from 2018-10-24 10-37-07.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58c6b01a3ac2041a00a63991/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f27b3dd7b768ee12365258424eab53444d04bea6d37ef5f22e7a985959e5d73b5670ce3c14a9b98b16bf01bb72834885e2bade5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5cf648e74b53ad173360e5647b.png)

**Comment by reinbach** [comment]
@adi130987 I made some tweaks to the formatting of the data in the exports, can you please see if that helps

**Comment by adi130987** [comment]
@reinbach looks better now, but I guess PDF export data tables should be improved. There is a very big table that just doesn't fit in pdf page.

**Comment by reinbach** [comment]
For PDF exports attachments are now links with `Attachment <num>` as the text for each link followed by any notes in `()`

This should prevent the column width getting out of hand.
