### ISSUE TITLE
Remove submit button from view page after submitted

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#188]
After an incident is submitted, remove the Submit button

**Comment by drzackyll** [comment]
<img width="991" alt="screen shot 2018-10-18 at 11 36 13 am" src="https://user-images.githubusercontent.com/8411545/47166577-84eab080-d2ca-11e8-8531-25d55c62c377.png">

**Comment by drzackyll** [comment]
connects to #193

**Comment by adi130987** [comment]
@drzackyll submit btn is already hidden after submission.
