### ISSUE TITLE
Fix 503 errors on demo

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#189]

**Comment by drzackyll** [comment]
![Screen Shot 2018-10-18 at 1.58.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455fb6b7191a379f117234f5d575ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19041c95df542e94550a1173667e2762431.png)

**Comment by daniel-tabarcea** [comment]
The root of the problem might be that sir.unicef.io/admin gets routed to the front-end container instead of the back-end one
