### ISSUE TITLE
Formatting problem with first page of exported incident PDF

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#195]
see screenshot

**Comment by drzackyll** [comment]
<img width="1234" alt="screen shot 2018-10-19 at 9 45 00 am" src="https://user-images.githubusercontent.com/8411545/47222017-c4290800-d383-11e8-8324-7411c04fb469.png">

**Comment by drzackyll** [comment]
relates to #230

**Comment by reinbach** [comment]
This should be resolved based on changes made in relation to #185
