### ISSUE TITLE
Possible issue with 'last edited on' field in incident

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#197]
maybe a regex error. see screenshot

**Comment by drzackyll** [comment]
![Screen Shot 2018-10-19 at 10.29.13 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455fa6b7191a379ef0c2958415e4dbc30254d58eeb9cb74fce36f34985619e883655922cf3919adbd871eb608ba208a1d8db1bcde4a94fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e84453a611366be270366e0a.png)

**Comment by adi130987** [comment]
This issues is already fixed
