### ISSUE TITLE
Restore removed backend validations from incident forms

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#199]
The backend validations were removed to account for sexual assault special cases.

**Comment by daniel-tabarcea** [comment]
This issue is referring to adding conditional validations for `/api/incidents/` and `/api/incident_involed/` based on whether or not the selected type is Sexual assault

**Comment by daniel-tabarcea** [comment]
Tried creating an incident, category Abduction with an empty City and the back-end accepted it as a valid entry. This is not by any means high priority, but at some point we should get back to fixing it

**Comment by reinbach** [comment]
Is `City` field meant to be a required field on Incidents?

**Comment by drzackyll** [comment]
Hmm... good question. I think so

**Comment by daniel-tabarcea** [comment]
`Target`, `Injuries` and `City`  should be optional only if the incident subcategory is one of `Sexual assault`, `Sexual harassment`, `Stalking`, `Rape`

**Comment by reinbach** [comment]
Validation has been updated in the backend

**Comment by daniel-tabarcea** [comment]
I can save an armed conflict with no injuries or city, the api only returned an error for the target field

**Comment by reinbach** [comment]
This has been fixed
