### ISSUE TITLE
Fix snags in AD login process

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#200]
A significant portion of the time, login to SIR via Azure AD fails with an error that can be seen on the attached screenshot.

Idea: does clicking to allow redirects and popups from sir.unicef.io fix the problem?

**Comment by drzackyll** [comment]
<img width="485" alt="screen shot 2018-10-20 at 10 17 52 pm" src="https://user-images.githubusercontent.com/8411545/47262451-377f6680-d4b7-11e8-9714-725c118f3b14.png">

**Comment by adi130987** [comment]
@drzackyll this issue is caused by unauthorized redirect after login. All redirect URLs must be added in Azure App config.

**Comment by drzackyll** [comment]
Most recent error (this is in my local env): ![Screen Shot 2018-10-22 at 7.33.46 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f16b7191a37ff111284f5b595edd3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19041c95df24be34d5da61b3361e4732431.png)
