### ISSUE TITLE
Create faked login process as a contingency

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#201]
We need to have a 'faked' login process ready in the event that Azure AD login does not work reliably. This would involve something similar to the login process that we had before integration, but where we have people enter their unicef email to login, disregard the password field, and allow them to inhabit the appropriate role in the app. This is a high priority.

**Comment by adi130987** [comment]
`something similar to the login process that we had before integration` old login still works (`/admin/login`).

**Comment by drzackyll** [comment]
@adi130987 does this work on the demo site? i tried in incognito just going to `/admin/login`, signed in, but then was redirected to `/login` to use the AD process.
