### ISSUE TITLE
Sexual assault backend validations

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#202]
Still have 3 validation errors when sexual assault is selected.

**Comment by drzackyll** [comment]
<img width="991" alt="screen shot 2018-10-21 at 9 43 37 am" src="https://user-images.githubusercontent.com/8411545/47267743-ee123400-d515-11e8-9248-e79d7a50530a.png">

**Comment by reinbach** [comment]
@drzackyll Not able to reproduce this, can you post the data sent to the backend please?

**Comment by drzackyll** [comment]
@reinbach 
`{description: "Sexual assault description", incident_date: "2018-10-15", incident_time: "12:12:00",…}
country: 3
description: "Sexual assault description"
incident_category: 1
incident_date: "2018-10-15"
incident_subcategory: 18
incident_time: "12:12:00"
injuries: ""
latitude: ""
longitude: ""
note: ""
on_duty: false
press_coverage: ""
region: 2
reported: false
street: ""
threat_category: 1
weapons_used: []`

**Comment by reinbach** [comment]
@drzackyll `latitude/longitude` need to be passed in as `null`, and I believe that the FE folks are making that change.

Otherwise validation has been dropped.
