### ISSUE TITLE
Errors with email system

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#203]
See screenshot. Need to make sure these emails are being sent.

**Comment by drzackyll** [comment]
<img width="260" alt="screen shot 2018-10-21 at 9 43 00 am" src="https://user-images.githubusercontent.com/8411545/47267763-18fc8800-d516-11e8-8dd8-6a5e7d805089.png">

**Comment by drzackyll** [comment]
<img width="1248" alt="screen shot 2018-10-21 at 9 40 51 am" src="https://user-images.githubusercontent.com/8411545/47267766-26b20d80-d516-11e8-95b4-79e3c6b1bff6.png">

**Comment by drzackyll** [comment]
email from should be `sir@unicef.org` as well

**Comment by reinbach** [comment]
Default from email address has been updated to `sir@unicef.org` in settings

**Comment by reinbach** [comment]
@drzackyll values now show correctly in admin section
