### ISSUE TITLE
Users endpoint not being populated

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#206]
The auto complete dropdown has no content. So checked the users endpoint and it returns an empty array.

**Comment by reinbach** [comment]
Now forcing relevant person record to be created for users, so we have complete data in endpoint

**Comment by drzackyll** [comment]
Not sure if this is related, but looking at the `Review` tab, the dropdowns for the people who would 'sign' the incident report should be populated only with the names of the appropriate people. I created a random person in the UN Personnel impact section and that person's name shows up in the reviewer dropdowns. But no other names show up there.

I assigned myself the role of a legal reviewer, so I should be able to see my name in the dropdown. tagging @daniel-tabarcea and @adi130987 too
