### ISSUE TITLE
Cannot add impact

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#212]
I am pretty sure I granted permission for impacts to Country Adviser team type. But when I submit I get the following

**Comment by drzackyll** [comment]
![Screen Shot 2018-10-22 at 1.14.35 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f16b7191a379f1132f4f5c5a5ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19141c95df24be34f5da1103461e1772431.png)

**Comment by drzackyll** [comment]
description: "Minor injury"
impact: 6
incident: "9"
person: {first_name: "Roger ", last_name: "Bevins", email: "", index_number: "", job_title: "", agency: 5,…}
agency: 5
category: 1
city: 1
country: 18
date_of_birth: "2018-10-03"
email: ""
first_name: "Roger "
gender: "male"
index_number: ""
job_title: ""
last_name: "Bevins"
nationality: 198
un_official: true
status: "On duty"

**Comment by reinbach** [comment]
Has this been resolved? Default permissions have been updated (#216)

**Comment by drzackyll** [comment]
As far as I can tell, this is resolved.
