### ISSUE TITLE
500 0n edit un-personel impact

### ISSUE THREAD

**Issue by acory** [unicef/sir-releases#222]
Create impact of type `Sexually assaulted`
Fill in only required fields, Save
Try to edit by changing Category , or Gender  or Duty station city or other fields in the person details area

Issue:  500 error response
KeyError at /api/incident_involved/2/
'id'
Request Method: PATCH
Request URL: http://localhost:80/api/incident_involved/2/

NOTE: edit works if Description is edited for example

**Comment by drzackyll** [comment]
Can confirm this is still an issue.

**Comment by reinbach** [comment]
@drzackyll made some tweaks on this endpoint, should be fixed now
