### ISSUE TITLE
Endpoints failing when not logged in on admin side also

### ISSUE THREAD

**Issue by acory** [unicef/sir-releases#223]
Log in to admin /login
Log in with Azure 
Go to incidents list , notice there are incidents
Go to admin side and Logout 
Come back to incidents list, Refresh

Issue:
 Incidents list is empty, the  endpoint /api/incidents/ returns an empty array despite having the required credentials sent, the JWT is there
And http://localhost:8081/api/comments/ returns 403

**Comment by drzackyll** [comment]
I'll second this. Went to try to test file upload I can open an incident, click to upload a file, then I get prompted to log in to the admin panel. If I cancel, I receive a 401 from `/api/incident_attachments`. This appears to be on both local and demo environments.

**Comment by drzackyll** [comment]
see my comments/screenshots on #170

**Comment by daniel-tabarcea** [comment]
As an update, now every request fails with 403 if i'm not logged in to the admin side

**Comment by drzackyll** [comment]
I'm adding a critical label to this

**Comment by drzackyll** [comment]
Even when logged into Admin Panel, I get a `500` on `/api/users/`, `/api/incidents/`, and `/api/incident_involved/` with the following response (very similar for each):

`ProgrammingError at /api/users/
column core_person.city does not exist
LINE 1: ..._person"."country_id", "core_person"."region_id", "core_pers...
                                                             ^
`

**Comment by reinbach** [comment]
@drzackyll for the core_person.city does not exist error, try and rebuild the backend/db from scratch. Should resolve it

**Comment by drzackyll** [comment]
@reinbach i deleted backend image and container and volumes folder. rebuilt but got the same errors for the same endpoints

**Comment by reinbach** [comment]
@zack did you also remove the db image and container? If so, can you create a separate issue related to the person.city does not exist then. I think it is a different issue than these 403 response when not logged in to the admin section

**Comment by drzackyll** [comment]
yeah will do

**Comment by reinbach** [comment]
This should be resolved now
