### ISSUE TITLE
400 on Create Un Programme impact

### ISSUE THREAD

**Issue by acory** [unicef/sir-releases#226]
Request body:
{
agency: 6
area: 1
country: 1
description: "DESC6"
impact: 4
incident_id: "26"
programme_type: 2
scope: 1
}

Response :
area: ["Invalid pk "1" - object does not exist."]

**Comment by daniel-tabarcea** [comment]
Yes, we still have issues with the input for Area, anything other than null will cause an error.  
@drzackyll can you please get more info on what Area is supposed to be for the impacted programme form? From what i remember in SSIRS it was a city if the selected scope was city,  a country if the scope was country and for the others there was no data. And if we do not get an appropriate answer in due time, can we consider changing this to plaintext?

**Comment by drzackyll** [comment]
relates to #147

**Comment by drzackyll** [comment]
Ok finally got a little more clarity on this. Going to keep the `Country` dropdown. Keep the `Geographical Scope` dropdown, but the options will change. The options are: `SRM Area` and `Designated Area`. `Area Impacted` will then be an open text field.

**Comment by reinbach** [comment]
Update scope default options.
Area field is now a text field
