### ISSUE TITLE
Need to add denomination field or default for property values in impacts

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#232]
Impacts > UN Property > Value

Just put `($USD)` or something next to it.

**Comment by drzackyll** [comment]
@daniel-tabarcea  They're hoping perhaps to have a dropdown instead with the various currencies. Is this a pain?

`AFN,ALL,DZD,USD,EUR,AOA,XCDARS,AMD,AWG,AUD,AZN,BSD,BHD,BDT,BBD,BYN,BZD,XOF,BMD,BTN,BOB,BAM,BWP,BRL,BND,BGN,BIF,KHR,XAF,CAD,CVE,KYD,CLP,CNY,COP,KMF,CDF,NZD,CRC,HRK,CUP,CZK,KPW,DKK,DJF,XCD,DOP,EGP,ERN,ETB,FJD,XPF,GMD,GEL,GHS,GTQ,GNF,GYD,HTG,HNL,HKD,HUF,ISK,INR,IDR,IRR,IQD,ILS,JMD,JPY,JOD,KZT,KES,KWD,KGS,LAK,LBP,LSL,LRD,LYD,CHF,MOP,MGA,MWK,MYR,MVR,MRU,MUR,MXN,MNT,MAD,MZN,MMK,NAD,NPR,ANG,NIO,NGN,NOK,OMR,PKR,PAB,PGK,PYG,PEN,PHP,PLN,QAR,KRW,MDL,YER,RON,RUB,RWF,SHP,WST,STN,SAR,RSD,SCR,SLL,SGD,SBD,SOS,ZAR,SSP,LKR,SDG,SRD,SZL,SEK,SYP,TJS,TZS,MKD,THB,TOP,TTD,TND,TRY,TMT,UGX,UAH,AED,GBP,UYU,UZS,VUV,VES,VND,ZMW`

**Comment by daniel-tabarcea** [comment]
No an issue, but we'll need an API update for this, a static data endpoint for all the denominations and a change to the incident impact api. If that's ok, i'll make tickets for the required changes
