### ISSUE TITLE
Many of the dropdowns to auto populate staff members are not enabled

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#236]

**Comment by drzackyll** [comment]
relates to #184

**Comment by reinbach** [comment]
@drzackyll Can we get more details on this? Is this a frontend issue? The user endpoint would be used for any staff members to populate the dropdown.

**Comment by drzackyll** [comment]
@reinbach hard to tell at this point exactly what i was talking about... but i think it may be that the dropdown isn't populated with the users from AD. from demo:
<img width="906" alt="screen shot 2018-11-09 at 12 45 08 pm" src="https://user-images.githubusercontent.com/8411545/48279041-5ec5b580-e41d-11e8-873d-e287303f0405.png">

**Comment by reinbach** [comment]
@drzackyll I think the issue may be that we may not always get the `first_name` and `last_name` from Azure AD, so these fields are blank. I've added `username` to the payload.

@daniel-tabarcea Should I add a field to the payload (eg `display_name`) that is attempts to use `first_name` and `last_name`, but if no data there to fall back to `username` and/or `email`?

**Comment by drzackyll** [comment]
@reinbach why do we not get `first_name` and `last_name`? or is there a `name` field or something that combines them? The AD profile I'm using on my local has my name assigned to it if I look at my profile in the azure portal. But when I check the `profile` endpoint on SIR, it looks like only my `username` is populated.

**Comment by reinbach** [comment]
@daniel-tabarcea I've gone and added `display_name` field to the payload. This is an attempt to ensure we have some value for the person. It works on a few values.

@drzackyll there is also display name field also being sent/provided by AD, I've incorporated that into the mix, to help ensure we have a value.
