### ISSUE TITLE
Update Review tab

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#237]
The review fields for incidents are not fully functional. Will discuss implementing a "sign" button that conditionally appears for the appropriate users.

**Comment by daniel-tabarcea** [comment]
Whenever the chance comes up, can you please inquire about the placement of the comment box, the approve button and the reject button?

**Comment by drzackyll** [comment]
relates to #215

**Comment by drzackyll** [comment]
They'd like the approve/reject first, comments, then reviews.
