### ISSUE TITLE
On new incident form, Weapons Used dropdown doesn't save

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#241]
I selected `other` from the dropdown, saved as draft, went back to the incident and the dropdown was blank.

**Comment by drzackyll** [comment]
<img width="736" alt="screen shot 2018-10-30 at 9 27 52 am" src="https://user-images.githubusercontent.com/8411545/47721336-450abe00-dc26-11e8-8391-578fe99b2dc8.png">

**Comment by reinbach** [comment]
@drzackyll is `Weapons used` still an option, I'm not seeing it on the frontend anymore

**Comment by daniel-tabarcea** [comment]
Yes, but you have to select incident category: security first

**Comment by reinbach** [comment]
Backend was not saving the weapon information correctly. This has been fixed.
