### ISSUE TITLE
Request again to have new incidents since last login

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#248]
They're very interested in seeing highlighted any new incidents that have been reported since the last time the user logged in. If this is a large request, they may not go for it.

**Comment by daniel-tabarcea** [comment]
@reinbach is it difficult to add the last login date to the repose for the profile endpoint? If we can get that information, the rest of this ticket would only be front-end work

**Comment by reinbach** [comment]
@daniel-tabarcea we should be able to do that

**Comment by daniel-tabarcea** [comment]
I've created #272 for that change request
