### ISSUE TITLE
Can emails link directly to incident?

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#262]
When a notification email is sent, is it possible to have it include a link directly to the incident in question?

**Comment by reinbach** [comment]
@drzackyll Incident link has been fixed in the notifications. You'll want to update the notification templates, with the following command in backend `python manage.py update_notifications`

**Comment by drzackyll** [comment]
@reinbach ahh ok. i ran this command and now have templates. i can see that emails are generated, but only end up in the `queued` status, so they aren't being sent. and it looks like a link is generated, but right now it looks like it'll point the user to an endpoint for the incident rather than the incident view screen on SIR.

example of generated link:
`http://localhost:80/api/incidents/5/`

example of the preferred link:
`http://localhost:8081/incidents/view/5`

**Comment by reinbach** [comment]
@drzackyll links have been updated to be those of the frontend now

**Comment by drzackyll** [comment]
@reinbach actually a quick tweak to this. it probably makes sense to send people to the history tab since that will hold any comments that the RSA/HQ make about what needs to be addressed to resubmit. an example of that would be: `http://localhost:8081/incidents/history/8/list`

Should have realized that sooner. Sorry for the back and forth!

**Comment by reinbach** [comment]
@drzackyll link has been updated to the incident's history page in the notifications

**Comment by drzackyll** [comment]
great, thanks!
