### ISSUE TITLE
Enable more than 255 characters for Description field in

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#267]
I think this might be backend validation

**Comment by drzackyll** [comment]
![Screen Shot 2018-11-05 at 12.50.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f66b7191a379ed0c2e51415d46bc21254d58eeb9cb74fce36f34985619e883655922cf3919adbd871eb608ba208a1d8db1bcde4a94fa2137a5dad11b61435c52dcbd4f3fb29842c259f34fe04951a4103364e776306e0a.png)

**Comment by reinbach** [comment]
Description now allows more characters, changed to a text field and not to a limiting charfield
