### ISSUE TITLE
Error when adding country in admin panel

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#270]
See screenshot

**Comment by drzackyll** [comment]
![Screen Shot 2018-11-06 at 3.03.20 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f56b7191a37bf112284f5d5f5ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19141c95df24ae44e51a2143365e5772431.png)

**Comment by reinbach** [comment]
Fix has been pushed for this, make sure migrations are run, or rebuild backend
