### ISSUE TITLE
500 errors even if logged in to admin panel

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#271]
Even when logged into Admin Panel, I get a `500` on `/api/users/`, `/api/incidents/`, and `/api/incident_involved/` with the following response (very similar for each):

`ProgrammingError at /api/users/
column core_person.city does not exist
LINE 1: ..._person"."country_id", "core_person"."region_id", "core_pers...
                                                             ^
`

**Comment by reinbach** [comment]
this should be resolved now. will need to rebuild backend locally

**Comment by drzackyll** [comment]
seem's like it's fixed! thanks
