### ISSUE TITLE
Attachments not viewable

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#274]
After an attachment is uploaded, the link to view the file does not work. See screenshots

**Comment by drzackyll** [comment]
![Screen Shot 2018-11-07 at 2.40.41 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f46b7191a37af1162b4f5b5e5ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df24ae74c5ca3113462e2722431.png)
![Screen Shot 2018-11-07 at 2.40.18 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f46b7191a37af1162b4f5e575ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19041c95df24ae74c5ca3113462e3742431.png)
![Screen Shot 2018-11-07 at 2.39.37 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f46b7191a37af111224f5c585ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df24ae74c5ca3113462e3722431.png)

**Comment by drzackyll** [comment]
whoops connects to #170

**Comment by reinbach** [comment]
Fixes issue with media files being displayed by backend. You may need to rebuild proxy and backend containers for this to work locally

**Comment by drzackyll** [comment]
getting a little different error now:
![Screen Shot 2018-11-12 at 12.36.44 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f16b7191a379ed0c2857415b4abc21254d58eeb9cb74fce36f34985619e883655922cf3919adbd871eb608ba208a1d8db1bcde4a94fa2137a5dad11b61435c52dcbd4f3fb29843c259f34fe34d51a011306be1703f6e0a.png)

**Comment by reinbach** [comment]
@drzackyll I'm not able to reproduce this. What steps are you taking to see this error

**Comment by drzackyll** [comment]
@reinbach it appears to work now! thanks!
