### ISSUE TITLE
Review fields values

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#276]
It looks like the incidents endpoint provides a field for `created_by_user` whereas impacts endpoints like evacuations have an equivalent field that is named `created_by_user_id`. This results in the incident created by field listed as N/A.

**Comment by daniel-tabarcea** [comment]
I wouldn't tackle this is a front-end issue, i would rather have the API return a more consistent naming scheme for review fields. I don't see any reason why these fields should not all be uniform

**Comment by daniel-tabarcea** [comment]
@reinbach  for the endpoints 
`/api/incidents/` and `/api/events/`  can you change `created_by_user` to `created_by_user_id` please?

**Comment by reinbach** [comment]
@daniel-tabarcea the fields on those endpoints have been updated
