### ISSUE TITLE
Permissions problems

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#288]
Looks like there might be some problems with permissions. I'm logged in with an account that should have the permissions of a Country Security Adviser. The `Add Incident` option is missing from the side menu. I can manually go to the proper URL though. If I create an incident and save it, there are then no buttons to do anything with it except cancel. No submit, no edit, no delete.

I noticed that some functions that show/hide buttons check `incident.unsynced`, which doesn't appear to be a populated value and doesn't get returned from the endpoint.

**Comment by drzackyll** [comment]
![Screen Shot 2018-11-12 at 4.04.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f16b7191a37cf1122f4f5d575ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df249e14853a21a376be7702431.png)
![Screen Shot 2018-11-12 at 3.57.57 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f16b7191a37bf1172c4f5a585ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19141c95df249e14853a21a376be6712431.png)

**Comment by daniel-tabarcea** [comment]
I'll start work on it tomorrow, now that we have the more granular permissions we should be able to fix this and a few other  related bugs

**Comment by drzackyll** [comment]
Cool, sounds good

**Comment by daniel-tabarcea** [comment]
removing the back-end label as this is purely a front-end issue
