### ISSUE TITLE
CSA user should not have ability to "sign" in review tab

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#294]
I gave myself CSA role and was able to sign my own report, and before I submitted it.

**Comment by daniel-tabarcea** [comment]
I can not reproduce this. I tested with a CSA user and could neither submit nor sign anything in created status. Can you check if the user had superuser status?

**Comment by daniel-tabarcea** [comment]
As a follow-up, CSA and RSA users seem to have permissions to comment but not to view or submit incidents. Aren't CSAs and RSAs the ones who are to add and submit incidents?
Edit: created ticket #303 for missing view permissions

**Comment by drzackyll** [comment]
@daniel-tabarcea i see the problem: i was signed in to the admin panel, which was allowing me to do just about whatever i wanted. and yes, you are right CSAs are primarily the ones creating incidents (and i think RSAs too) so they should have those permissions to add and submit.
