### ISSUE TITLE
History tab not showing who made changes

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#296]
See screenshot

**Comment by drzackyll** [comment]
![Screen Shot 2018-11-19 at 9.40.52 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455fa6b7191a371f1162b4f5a5d5edd3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19141c95df249e74e5da113306bee762431.png)

**Comment by drzackyll** [comment]
copying a screenshot from slack conversation here:
![Screen Shot 2018-11-23 at 3.30.10 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f06b7191a37bf1112b4f5e5f5ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df248e14d50a410316ae0752431.png)

**Comment by daniel-tabarcea** [comment]
Is the issue with comment owner still happening on the demo server?

**Comment by drzackyll** [comment]
It looks like it is happening on the demo server still.
