### ISSUE TITLE
500 error/no redirect on incident submission

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#298]
When I submit an incident, I get a 500 error in the console and the page does not redirect. But if I reload the incidents list, the status of that incident shows as submitted.

**Comment by daniel-tabarcea** [comment]
```ValidationError at /api/incidents/8/submit/```
```{'template_name': ['No such EmailTemplate: incident-submitted']}```
As long as we remember to create all the necessary email templates after deploying we should be fine. 
Is there a list of all the templates required anywhere that we can check against after deploying?

**Comment by reinbach** [comment]
I'm looking into ensuring that the creation of these necessary email templates happen during deploy

**Comment by reinbach** [comment]
Email templates are now automatically created when building the backend

**Comment by drzackyll** [comment]
see #299
