### ISSUE TITLE
Error when creating email template in admin panel

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#299]
When i click to save email template, i get the following error

**Comment by drzackyll** [comment]
![Screen Shot 2018-11-19 at 10.05.15 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455fa6b7191a379ef0c2b54415e4bbc30254d58eeb9cb74fce36f34985619e883655922cf3919adbd871eb608ba208a1d8db1bcde4a94fa2137a5dad11b61435c52dcbd4f3fb29b4ac259f34fe34b56ad1a3e66e270366e0a.png)

**Comment by reinbach** [comment]
@drzackyll A fix has been pushed for this, you will want to re-build the backend. The email templates should be automatically created during the build

**Comment by drzackyll** [comment]
@reinbach i went to admin panel after rebuilding but it looks like no email templates are shown in there. in either case, i was able to create one successfully. i changed the test RSA account's email address to be my unicef one then used my CSA account to submit. i haven't yet received an email (though it's possible there's just a delay). will continue checking.

**Comment by drzackyll** [comment]
see #262 for latest
