### ISSUE TITLE
Updates to Approval and Review

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#304]
From email:
`The Regional Security Advisers and the HQ Security Team can review the incident simultaneously.  EOD, DHR, Legal, Staff Wellbeing and DFAM will only receive a notification once the HQ Security Team has reviewed the SIR. For gender-based security incidents, the HQ Security Team will only send it to Staff Wellbeing and Legal as required.  The HQ Security Team should be able to send a SIR to specific reviewer groups.`

**Comment by reinbach** [comment]
Notification is now being sent to the review teams when incident is approved

**Comment by drzackyll** [comment]
@daniel-tabarcea @reinbach where do we stand on this one?

**Comment by reinbach** [comment]
@drzackyll when the incident is `approved` notification is sent to all reviewers.
There is an endpoint `/api/incident/<incident_id>/alert/<group_id>/` that sends an alert to a specific group, but it is for a managed group.

I would need to add another endpoint that allows frontend to target a specific review team;
e.g. `/api/incident/<incident_id>/alert/team/<team-type-id>/`

**Comment by reinbach** [comment]
added new endpoint `/api/team_types/` that returns payload `{"id": <int>, "name": <str>}`

Pass in the id from this payload for the team type to send the alert to;
`/api/incident/<incident_id>/alert/team/<team-type-id>/`
