### ISSUE TITLE
Make sure HQ team can see all incidents past created

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#305]
The HQ team should be able to see all incidents from submitted status on. Right now on my local, only one incident is being displayed, the one that is in "Submitted" status. Approved incidents are not showing up.

**Comment by reinbach** [comment]
@drzackyll Does your HQ team have any region/country restrictions?
I'm not able to reproduce this issue

**Comment by drzackyll** [comment]
No, they just have the default permissions of the HQ team.

Here's what CSA can see:
![Screen Shot 2018-11-23 at 8.35.48 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f06b7191a370f1112e4f5b575edd3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df249e84555a6133463e2702431.png)

And what HQ can see:
![Screen Shot 2018-11-23 at 8.38.10 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f06b7191a370f111234f5e5f5edd3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df249e84555a7123464e0712431.png)

HQ ought to be able to see case `I000005` on their incidents list.

**Comment by reinbach** [comment]
But that incident has been `rejected` and so sent back to the CSA to correct. So we want rejected incidents to continue to show up for HQ?

**Comment by drzackyll** [comment]
ok, probably fine not to have rejected events appear. i thought i recalled another incident not appearing, but that was a couple days ago and i can't reproduce. perhaps i'll close this and keep an eye on it.
