### ISSUE TITLE
Lock impacts on submit

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#306]
It looks like not only can impacts be edited/added after submission, perhaps all users have ability to do this? Was able to have RSA add an incident to a form submitted to them.

**Comment by reinbach** [comment]
@drzackyll All teams can change an incident, but not impacts. Country, Region, and HQ can also manage the impacts. At what point do we want to lock down the ability to change the incident and impacts? Once submitted, only able to approve, reject, comment, and review?

**Comment by drzackyll** [comment]
@reinbach I think if we consider impacts just part of the incident report, the whole report should only be editable by the person who creates it. it would remain editable until they `submit`. once submitted, it locks. but then of course if it's rejected, the person who created it should be able to edit before submitting again. Yes, once submitted, I think the only actions should be approve, reject, comment, review.

**Comment by reinbach** [comment]
@drzackyll I've updated the permissions, and added validation to ensure incidents are not updated after being submitted.
