### ISSUE TITLE
Legal reviewer does not have enabled "Sign" button

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#308]
see screenshot

**Comment by drzackyll** [comment]
![Screen Shot 2018-11-21 at 3.44.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f26b7191a37bf1162f4f5f585ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19041c95df249e94e56a41a3e62e4702431.png)

**Comment by drzackyll** [comment]
staff wellbeing permissions for your reference:

![Screen Shot 2018-11-21 at 3.49.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f26b7191a37bf116224f5f585ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19141c95df249e94e56a2133563e07e2431.png)

**Comment by drzackyll** [comment]
EOD is able to sign but `EOD review by` is not populated.
![Screen Shot 2018-11-21 at 3.54.23 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f26b7191a37bf1172f4f5d5c5ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19041c95df249e94e56a3123363e1772431.png)

profile for user:
`id	5
agency	null
title	
first_name	
last_name	
contact	
username	zack_adams@yahoo.com
email	zack_adams@yahoo.com
date_of_birth	null
gender	
nationality	null
type_of_contract	
index_number	
job_title	
last_modify_date	2018-11-21T15:20:12.060576Z
un_official	false
teams	[…]
0	{…}
id	4
created_on	2018-11-20T18:57:16.757736Z
name	EOD
created_by_user	null
team_type	4
region	null
country	null
display_name	zack_adams
permissions	[…]
0	add_comment
1	change_incident
2	change_comment
3	delete_comment
4	view_comment
5	view_incident
6	eod_review_incident
last_login	2018-11-21T15:20:14Z`

**Comment by drzackyll** [comment]
same as above with DHR:
![Screen Shot 2018-11-21 at 4.03.09 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f26b7191a37cf112284f5f565ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19141c95df249e94e51a7133467e77f2431.png)

**Comment by drzackyll** [comment]
and again with DFAM
![Screen Shot 2018-11-21 at 4.07.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f26b7191a37cf1122c4f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19041c95df249e94e51a01a3567e2722431.png)

**Comment by reinbach** [comment]
What permissions should staff wellbeing team have?

**Comment by drzackyll** [comment]
@greg i believe same as the other review groups. was just including that screenshot for @daniel-tabarcea reference

**Comment by daniel-tabarcea** [comment]
There was a front-end typo for the legal reviewer, i've pushed a fix to develop
