### ISSUE TITLE
Reviewers able to see incidents in Submitted status

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#312]
I have a DFAM user whose incident list includes an incident in submitted status. They should only be seeing approved incidents.

**Comment by drzackyll** [comment]
![Screen Shot 2018-11-23 at 2.28.09 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f06b7191a37af110234f5f565ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df248e14d54a0133063e6732431.png)

**Comment by drzackyll** [comment]
I just tested DHR reviewer and it's the same. I imagine all reviewer teams experience this behavior.

**Comment by reinbach** [comment]
Are they only allowed to see an incident once it has been approved?

**Comment by drzackyll** [comment]
Yes. Officially they should only see an incident once it is approved and the hq “sends” it to a particular review group. But for now just restricting them to approved status should be enough.

**Comment by reinbach** [comment]
Submitted incidents no longer show up for reviewers
