### ISSUE TITLE
Add new incident subcategories

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#315]
They want the following subcategories added: 
Sexual Harassment
Stalking

They may want to include Rape as well, but I asked them if that is not considered sexual assault and am waiting for a response.

**Comment by daniel-tabarcea** [comment]
I've hit a snag, i sent this to the api:  
```
{
    "person": {
        "first_name": "",
        "last_name": "",
        "email": "",
        "index_number": "",
        "city": "",
        "job_title": "",
        "region": 38,
        "country": 157,
        "un_official": true
    },
    "incident": "4",
    "status": "On duty",
    "impact": 12,
    "description": "sssssss"
}
```
and got this: 
```
{"person":{"last_name":["This field may not be blank."],"first_name":["This field may not be blank."]}}
```

impact no. 12  is `Stalking`
Same issue with imact no. 11, `Sexual harassment`

**Comment by reinbach** [comment]
@daniel-tabarcea pushed a fix for this, and added "Rape" as a category

**Comment by daniel-tabarcea** [comment]
Works as expected now
