### ISSUE TITLE
Clean up regions list

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#318]
The list of regions has duplicates (eg. MENA and Middle East and North Africa), with some countries assigned to one and some to the other (eg., Lebanon is in Middle East and North Africa, Kuwait is in MENA). Let's stick with the acronym versions. Check for typos in countries list too.

**Comment by reinbach** [comment]
What are the acronyms for the following regions;
- `Western Europe`
-  `North America`

**Comment by reinbach** [comment]
I've cleaned up the Demo site's regions and countries. Locally you'll want to rebuild your db with the latest push.

**Comment by drzackyll** [comment]
Hi @reinbach sorry for the delay. I think western european countries can be included in the ECARO region and north american countries in the LACRO region if it's not too late

**Comment by reinbach** [comment]
@drzackyll Countries have been updated.

Locally you can run `python manage.py init-setup --regions`, which will leave `Western Europe`, and  `North America` regions in place, but updates the countries. 
You can manually remove those. May need to remove association with Incidents.

SIR demo has been updated.

**Comment by drzackyll** [comment]
great, thank you!
