### ISSUE TITLE
Update UNICEF staff types

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#320]
Currently the types are limited to Consultant and UNV International. Add FT Staff, TA, and UNV National.

Does this information come from Active Directory?

**Comment by reinbach** [comment]
I believe this information came from the docs and screenshots.

**Comment by reinbach** [comment]
@drzackyll Staff types have been updated

**Comment by drzackyll** [comment]
@reinbach I mean do we know if the staff type is a field that can be populated from AD when a particular user is selected (on UNICEF personnel impacts)?

**Comment by reinbach** [comment]
Not in the default mapping we have setup at the moment.
Would need to check what we're getting from AD in production, as we use a different AD instance in dev
