### ISSUE TITLE
Fix export functionality

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#322]
There is a bug with PDF export (and double-check the other formats to make sure they are working correctly).

**Comment by reinbach** [comment]
Issues appears when a large blob of text is used in the notes incident field

**Comment by reinbach** [comment]
Updated the rendering of PDFs to attempt to handle this more gracefully. But there is the case if notes are the length of a book, then the PDF export is not ideal. Just not setup to display the data cleanly and it would be better for the users to make use of the other types for export formats. So they can better massage the data display.

Is the PDF cannot handle the rendering of the data, then it will indicate this to the end user in the generated PDF.

**Comment by drzackyll** [comment]
@reinbach Do we know at what length the blob starts causing PDF rendering to fail? I think in the particular case that brought up this issue, the user input 771 characters. But he put it in the `Notes` field in incident details instead of the `Incident Description` field.

**Comment by drzackyll** [comment]
Is it possible `Incident Description` can handle that amount of text if the user put it in that field?

**Comment by reinbach** [comment]
I was testing with words, and when getting up to the ~500 words, that it started to cause issues. The issue though is that if we end up with a long description/note, and it ends up taking a whole page to show that info, we then have 1 row per page, and the columns are over multiple pages, so you end up with a pretty long document, which is not very handy.

**Comment by reinbach** [comment]
The rendering is not checking specific fields, it is a general thing if the page layout fails as a whole, it attempts to re-adjust things to a point.

**Comment by drzackyll** [comment]
Ok. Maybe i'll check with the business owners and see about making a max number of words/characters for all fields. And we can add a counter on the FE.

**Comment by drzackyll** [comment]
@reinbach Actually, an additional, related question. They're really pushing for the ability to export to `.doc`. I am pretty sure we discussed this before and I sort of recall Rob saying that it's just too much of a pain. Is that the case?

**Comment by reinbach** [comment]
@drzackyll we can add `.doc` to the list of options, the only thing is that it is similar to PDF in that it is not really suited for this sort of data
