### ISSUE TITLE
Is there any way to improve formatting of PDF exports?

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#330]
Had some complaints about some fields being cut off or all aligned to the right. Check into how much power we have to control formatting.

**Comment by reinbach** [comment]
@drzackyll Are they wanting the PDF in table column format? I don't think that works well for PDF as there are a number of columns and is spread over many pages.

**Comment by drzackyll** [comment]
see comment on #333

**Comment by reinbach** [comment]
Updates relate to #333
