### ISSUE TITLE
Add ability to export incidents as .doc

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#333]
How difficult is this to implement? I believe we pushed back against having this as an option but apparently they deem it critical.

**Comment by drzackyll** [comment]
related to #334

**Comment by reinbach** [comment]
@drzackyll this is the same issue as with PDF, the table column format is problematic. If they are OK with that, then we can go ahead and generate these files in `.doc` format.

**Comment by drzackyll** [comment]
@reinbach We got the ok to implement export in DOC and PDF formats for single incidents so that the formatting may be improved. Exports of multiple incidents would be CSV/XLS/XLSX only.

**Comment by drzackyll** [comment]
relates to #322

**Comment by reinbach** [comment]
@drzackyll  PDF format has been updated, I've not restricted the backend for PDF and DOC formats to a single incident. Frontend can allow single incident export for PDF and DOC formats, and not provide that format for multiple incidents.

**Comment by drzackyll** [comment]
@reinbach @daniel-tabarcea sounds good

**Comment by daniel-tabarcea** [comment]
What's the URL for exporting a single incident? i've tried `/api/incidents/4/?format=pdf` and got an error, something like `Response data is a ReturnDict, not a Dataset! Did you extend ExportMixin?`

**Comment by daniel-tabarcea** [comment]
![teh export error](https://user-images.githubusercontent.com/17467562/51754894-189bfc00-20c6-11e9-843b-dfd7dee74a95.png)

I'm getting this error, am i doing something wrong? I've removed both the docker backend container, image and volumes/backend folder

**Comment by reinbach** [comment]
@daniel-tabarcea No you're not doing anything wrong, looks like there is a bug. Looking into it now.

**Comment by daniel-tabarcea** [comment]
Exports as docx work as exepcted
