### ISSUE TITLE
Is it possible to add ability to share link to incident to a specific email address?

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#335]
There was a situation where a Syria security adviser was in Malaysia and an incident occurred. So the Syria adviser would need to fill out an SIR for that incident. If they submit, the MENA regional security adviser is notified but no one in Malaysia's region is notified. Request is for a text field where users can enter an email address to share the incident.

**Comment by reinbach** [comment]
@drzackyll The user needs to be in the system in order for them to be able to access/view the incident. Can we change that request to select a user, and the incident is sent to them? Not require that a free form email address be supplied?

**Comment by reinbach** [comment]
@daniel-tabarcea there is an endpoint available to send an incident to a specific user
`/api/incident/<incident-id>/alert/user/<user-id>/`

**Comment by drzackyll** [comment]
I imagine having a dropdown to select a user is fine. I believe they'd only be sharing it with another user in the system. I suppose whoever they share it (say it's the Malaysia Country Field Security Adviser) with would have to be give permission to see an incident created by someone else? I will double check with client to make sure dropdown is ok.

**Comment by drzackyll** [comment]
@greg @daniel-tabarcea they're ok with having a dropdown. can it be multiselect? and can the options displayed be [Name] - [Position Title] rather than email address?

**Comment by daniel-tabarcea** [comment]
@reinbach the endpoint works ok in normal conditions, it seems to fail only for users created by `manage.py  createsuperuser` .
It looks like this: 

```
ValidationError at /api/incident/1/alert/user/3/
{'recipients': ['Item 1 in the array did not validate: This field cannot be blank.']}
```

**Comment by daniel-tabarcea** [comment]
@drzackyll I've put the dropdown where you can select the users to notify in the review tab, does it make sense having it there?

**Comment by reinbach** [comment]
Fixed the backend, ensure it does not attempt to use a blank value for email field

**Comment by drzackyll** [comment]
@daniel-tabarcea it doesn't seem totally intuitive, but i can't think of another place that would be better. i think review tab should be ok.
