### ISSUE TITLE
Ensure that EMOPS user does not have ability to permanently delete anything in admin panel

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#336]

**Comment by reinbach** [comment]
@drzackyll does this include the ability to manage the various categories and impacts etc? Not able to remove any of those?

**Comment by drzackyll** [comment]
I guess that depends on if deleting those will cause breaking change. Or is there some kind feature that allows for disabling a category option?

**Comment by reinbach** [comment]
There are blocks in place to prevent certain deletions from happening. For example you can't delete a country if being used by incident, person, or team etc. You have to remove the reference to the country in those records first.

**Comment by drzackyll** [comment]
Ok. Do you think that... say they decide sexual harassment is no longer a subcategory they want to use. But there are a couple incidents in the database with that subcategory selected. Will deleting sexual harassment from the subcategories list cause problems?

**Comment by reinbach** [comment]
In that instance they will be prevented from deleting the subcategory as it is related to an incident.

**Comment by drzackyll** [comment]
Ok good. But there is no ability for the EMOPS admin to remove the subcategory from the list that appears on the FE so future users won't be able to select it?

**Comment by reinbach** [comment]
I removed that ability, but can easily add it back if we need/want to
