### ISSUE TITLE
Remove Admin panel button for non-EMOPS users

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#342]
I guess they don't want all staff to have access... only people on EMOPS team to have the button appear on SIR.

**Comment by daniel-tabarcea** [comment]
I've made it so the admin button is visible only if the user has the `view_admin` permission.   
@reinbach  can you please add this permissions to the EMOPS team?

**Comment by reinbach** [comment]
@daniel-tabarcea I've added the `view_admin` permission, specifically it is `security.view_admin`, as I need to have the app name in there. Hope that works for you.

**Comment by daniel-tabarcea** [comment]
great, thanks
