### ISSUE TITLE
Ensure app complies with Class I security specifications

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#343]
See attachment

**Comment by drzackyll** [comment]
[Annex 4 Security Classification.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46c99a94269ac3fdcfdaba40b14ff9803006047f2817b022768ce029ab4b740f4d435cec03070511afbd9b21b4b36e788c0a02e9d96c5a71c73418acb8834db706ba748d1b97aaaec81d9ebc6278bec1da0d2c1417198ef55c30a49e4ccd5bf14fe44a5ca5017b.pdf)

**Comment by reinbach** [comment]
@drzackyll I would say that we mostly comply, we make use of certain systems (eg AD, hosting services etc) that are handled by other UNICEF departments/section that we do not control. So I'm making the assumption that they comply where applicable.

The reason we do not comply fully is the multi-factor authentication part for privileged accounts. We do not have this, we make use of AD to auth, and we do not require that that has multi-factor auth.
