### ISSUE TITLE
Fix active directory integration

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#344]
UNICEF staff dropdown in impacts is not populated with all unicef staff from AD. Sync is failing.

**Comment by drzackyll** [comment]
@reinbach did you hear back from vlatko about this?

**Comment by reinbach** [comment]
@drzackyll No, it looks like to me that this may get pushed to the frontend to get the list of UNICEF employees, as the backend does not have the necessary credentials

**Comment by reinbach** [comment]
@daniel-tabarcea The Azure AD url to get list of users should be;
`https://graph.microsoft.com/v1.0/users/`

See https://docs.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0 for me details
