### ISSUE TITLE
Add ability to 'archive' or disable certain items via admin panel

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#347]
relates to #336

Business confirmed they'd like to be able to remove certain items from taxonomy categories in the admin panel without breaking the site (similar to making a user inactive).

**Comment by reinbach** [comment]
@daniel-tabarcea Do you want me to remove these "inactive" items from the taxonomy payloads, or just add a flag `is_active`

**Comment by daniel-tabarcea** [comment]
Coming back to this, i think my request to have them removed from payloads altogether was not the right way to do it. 
Right now, if an option is disabled from the admin side it looks on the front-end as if it was never filled in, which may cause confusion. Can we get back at this and add either an `is_active: false` or `disabled` flag to these taxonomy items?

**Comment by reinbach** [comment]
Ok, `is_active` flag has been added to the payloads, and no longer filtered out

**Comment by daniel-tabarcea** [comment]
Thank you, i've made the changes on the front-end side also
