### ISSUE TITLE
Make history items visible only if correct permissions are in place

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#352]
For example, if a user does not have view impact permissions, impacts are still visible in the history tab

**Comment by daniel-tabarcea** [comment]
We should probably implement something similar on the back-end so the impact history endpoints check if the users have the view permissions. 
Should we just use the same permissions as we do when viewing impacts or should we use something more specific? 
@drzackyll @reinbach

**Comment by reinbach** [comment]
We can make use of the same view permission for the impact. If user can view impact, they can then view the impact history as well.

**Comment by reinbach** [comment]
I've updated the history view endpoints to expect the impact view permission, otherwise responds with 403
