### ISSUE TITLE
Problem with device location button

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#355]
Looks like there's an error. Screenshot attached.

**Comment by drzackyll** [comment]
![Screen Shot 2019-02-18 at 12.04.27 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216455fb6b7191a379ed0c2b55415d49bc21254d58eeb9cb74fce36f34985619e883655922cf3919adbd871eb608ba208a1d8db1bcde4a94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee14855ad16326ae77e3e6e0a.png)

**Comment by daniel-tabarcea** [comment]
I can't reproduce this, are there any particular conditions to generate this error?

**Comment by drzackyll** [comment]
I just went to create a new incident and clicked the geolocation button. Nothing populates the lat/long and this error appears in console. This seems to happen on all browsers (at least Chrome, Safari, Firefox). Here are errors from the latter two:
![Screen Shot 2019-02-21 at 8.58.41 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216456f26b7191a370f117234f5b5e5edd3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df34be64852a21a3064e5742431.png)
![Screen Shot 2019-02-21 at 9.00.40 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216456f26b7191a371f1122b4f5b5f5edd3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df34be64852a3133367e2732431.png)

**Comment by drzackyll** [comment]
i did some investigating and it was a problem where somehow location services was disabled on my laptop. not sure how that happened. but that seems to have been the culprit
