### ISSUE TITLE
Encrypt certain database columns

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#356]
Not a final list:
-incident description
-incident note
-incident city
-incident street
-incident latitude
-incident longitude
-personnel impact status
-personnel impact description
-personnel impact impact
-personnel impact first name
-personnel impact last name
-personnel impact nationality
-personnel impact gender
-personnel impact email
-personnel impact index number
-personnel impact category
-personnel impact job title
-personnel impact city
-details of submitting officer

**Comment by reinbach** [comment]
Fields have been encrypted. I should note that the Person Impact record can be linked to the user table, if the person impacted is an employee. The email address record in the Person Impact record is encrypted, but the email address in the potentially linked user table is not. We cannot encrypt the user table email address, as it is used for login purposes and it would limited our ability to perform login functionality.

With the change in showing employees via the front end fetching directly from azure AD, I don't see the link being set/created between Person Impact record and user table. But just wanted to note this.
