### ISSUE TITLE
Additional team type

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#366]
There are certain countries that have an additional layer of security staff. In these countries, there are a number of staff who may create incident reports, but who should not have the ability to submit them to RSAs. The country field security adviser for that country should be able to examine and make the submission to RSA.

**Comment by reinbach** [comment]
@drzackyll  Is it an option if we are able to just create a new Team Type that has the relevant permissions? Give it a meaningful name 
e.g. 
- `Country Field Security Advisers - No Submit` 
or
- `Country Field Security Advisers - Limited`

This should not require any changes on the front end then?

**Comment by drzackyll** [comment]
@reinbach If we did this, would the person with the full Country Field Security Adviser permissions (incl. submit) be able to see the incidents created by these users and submit them? Also, would other users with the limited (non-submit) permissions be able to see each other's incidents if they are in the same country?

**Comment by reinbach** [comment]
@drzackyll So I added another Country Field Security group `Country Field Security Advisers - Full` that is able to view incidents `created` by others with the same country.

So if we have both the `Limited` and `Full` Country groups in play, that should hopefully be able to work for this scenario?

**Comment by drzackyll** [comment]
@reinbach I think that's a sound solution. `The Country Field Security Advisers - Full` should probably also have edit and submit permissions too.
