### ISSUE TITLE
Create/update user search function

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#367]
3 letters minimum for search

**Comment by reinbach** [comment]
@drzackyll We are not able to both encrypt the data as well as be able to search on it.
The searching would happen on the `first_name`, and `last_name` fields, but those are currently encrypted.

Are we willing to remove the encryption on those fields?

**Comment by drzackyll** [comment]
Good question. This info wouldn't be attached to anything related to incidents right? It's just a list of all people with UNICEF credentials. I think I would say that if it's just a list of names, it is ok to keep it unencrypted.

**Comment by reinbach** [comment]
The user table `first_name` and `last_name` fields are not encrypted, so made the searching against those instead. Allows us to leave the person fields encrypted which are related to the incident. There is a relationship between the user and person fields where applicable, which does breakdown the whole encrypting aspect. 

To search for a user
`/api/users/?q=<search_string>` I don't add a limit on number of characters in the backend

**Comment by daniel-tabarcea** [comment]
I tried calling `http://localhost:8081/api/users/?q=zeke/` with GET and got no result. Zeke is one of the users i get if i call `/api/users/` with no query. I also tried searching for a known username and also got no result. Is this case-sensitive?

**Comment by reinbach** [comment]
No trailing `/` after the get param. It should not be case-sensitive

**Comment by daniel-tabarcea** [comment]
If i don't add the final slash i get a `301 Moved Permanently (from disk cache)` response and i get redirected to the link with the slash

**Comment by reinbach** [comment]
I'm not seeing that 301 redirect locally

**Comment by daniel-tabarcea** [comment]
Turns out it was a setup issue. Deleted the container and image for the backend, tried again and it works now
