### ISSUE TITLE
Changes to Events [BE]

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#371]
Add to new events the following fields:
-Lat/Long
-Incident Category
-Incident Subcategory
-Threat Category

Add to events list the following fields:
-incident category
-threat category

**Comment by drzackyll** [comment]
I'm guessing those would be "Event Category" and "Event Subcategory", but they would list the same options as in incidents

**Comment by reinbach** [comment]
Do some of these fields need to be encrypted as they are for Incidents?

**Comment by drzackyll** [comment]
I don't think so, since events are a bit more general and wouldn't really describe individuals
