### ISSUE TITLE
Clicking 'save' should not mean that an event/incident is submitted

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#75]
There should be a distinction between saving and submitting. Country security advisers should be able to create an incident or event and save it as a draft, then edit as they wish. Once they click submit, its status should change to submitted.

**Comment by drzackyll** [comment]
It looks like maybe in its current state, a status of 'submitted' means that it has been synced. But I think for the business people, 'submitted' signifies that the incident/event has been submitted to the security manager for review.

**Comment by daniel-tabarcea** [comment]
@reinbach is there a way to differentiate on the API a save from a submission?

**Comment by reinbach** [comment]
@daniel-tabarcea should we make use of the `status` field to handle this? So you can set that as/when you want to change it? At the moment `submitted` is the default value for status, we can add something else eg: `pending` or something similar?

**Comment by daniel-tabarcea** [comment]
@reinbach yes, we could do that

**Comment by saxix** [comment]
New incident start with state == `created`.there is now a new  endpoint to "submit" the incident.

- By default users with `ApprovalPermission` have now `SubmitPermission`, it can be changed using admin interface.
- `submitted_date` now refers to date of submission and not date of creation, so it is null when created.
- It not possible `approve` incident in `created` state
- We have now `created_by` and `submitted_by` fields
