### ISSUE TITLE
Remove "reported to police" checkbox on new incident page

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#79]

**Comment by drzackyll** [comment]
<img width="344" alt="screen shot 2018-08-31 at 1 25 34 pm" src="https://user-images.githubusercontent.com/8411545/44927121-654ef700-ad21-11e8-8971-480fd6654411.png">

**Comment by daniel-tabarcea** [comment]
just the checkbox or the entire section? at the moment checking the box uncovers a couple of inputs for "reported to" and "responsible party"

**Comment by drzackyll** [comment]
@daniel-tabarcea i have asked for confirmation, since this item does appear in the TOR annex. will update here.

**Comment by drzackyll** [comment]
@daniel-tabarcea  just remove it all

**Comment by daniel-tabarcea** [comment]
Fields reported, reported_to and responsible also need to be removed from the incident API.  @saxix can you have a look at it?
