### ISSUE TITLE
Replace the events and incidents tables on dashboard with a single table

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#81]
The table will have the following columns:
Case Number, Incident/Event, Category, Region & Country, Person, Date Created, Date Edited.

The case number can be generated by us; suggestion is 'I' followed by sequential numbers for incidents and 'E' followed by sequential numbers for events. (eg, I00134, I00135)

**Comment by drzackyll** [comment]
After those columns, there should be a column of icons (the edit icon to edit an incident if the incident isn't closed. if the incident is closed, the view icon should be present)

**Comment by drzackyll** [comment]
See also #82

**Comment by daniel-tabarcea** [comment]
Category, Region & Country, Person are not available for events, only for incidents. Also, since this is supposed to work on small displays like iphones i would advise against adding too many columns to the list

**Comment by drzackyll** [comment]
Since most users of the dashboard will be using computers, it sounds like the business owners are not too worried about the mobile interface for it. That said, they are now hoping that the fullscreen version includes ID, description (first 140 characters), country, synched?, status, date opened, category, sub-category, and incident type. The last three would show N/A for events. Then on mobile, the most important fields are ID, description, synced?, status and date created. The rest could be expanded clicking the arrow. (And I wonder if we could just give event rows a different background color... not sure if this is appropriate in terms of accessibility or not).
