### ISSUE TITLE
Add ability to enter names from outside of Active Directory

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#85]
There should be a way to indicate that the person involved is not in active directory (checkbox?). On selection, the following required fields appear:
First Name
Last Name
Job Title
Nationality
Gender
Employment Status/Type

**Comment by reinbach** [comment]
Made changes to how people and users are handled
- `users` are defined as those having access to the system, and are users that submit, update, and/or review incidents (`/api/users/`)
- `persons` are defined as those as either `primary person` or those `involved` with an incident (`/api/persons/`)

When adding an incident with people involved, we can either pass in `person_id` if person exists in the system or provide the data above, to create a new person.

Still working on having all people from Active Directory (AD), available at the `/api/person/` endpoint, with an indicator that they are an UN Employee. But the ability to enter names outside of AD is available now.

**Comment by reinbach** [comment]
@daniel-tabarcea @acory Just an FYI that changes have been made to the handling of `involved` with an incident based on this ticket.

Expected data for `involved` records;

To create a new person record;
```
{
   "impact": "",   <-- person impact see `/api/impact/person/`
   "injury": "",
   "first_name": "",
   "last_name": "",
   "job_title": "",
   "nationality": "",
   "gender": "",
   "type_of_contract": "",
}
```

To use an existing person record;
```
{
  "impact": "",   <-- person impact see `/api/impact/person/`
  "injury": "",
  "person_id: "",
}
```
`/api/persons/` endpoint is now available to get a list of persons, as well as to add/update person data
