### ISSUE TITLE
Incident sub-category "Sexual Assault" triggers change in which fields are required

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#90]
When someone is reporting Sexual Assault as an incident, the only required fields should be: Threat Category, Incident Category, Incident Sub-category, Description, Date/Time, and Country. The rest should be optional (this is to protect identities).

They've also asked that when Sexual Assault is selected, a pop-up or modal appears that informs the user that this is a category with special rules. The text for this will be coming from the business owners... perhaps create a blank modal for now with some lorem ipsum.

**Comment by daniel-tabarcea** [comment]
I think we should avoid any sort of modal dialog since this is supposed to work on a mobile device, but we can make a warning text appear on screen so the user is informed on the matter

**Comment by drzackyll** [comment]
Ok sounds good to me

**Comment by drzackyll** [comment]
connects to #83

**Comment by adi130987** [comment]
This is already implemented. Closing...
