### ISSUE TITLE
Endpoint for personnel categories static data

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#92]
We need an endpoint for personnel categories as used in the incidents impact on personnel form.
Each item should have an id and a name

**Comment by reinbach** [comment]
This is available at `/api/impacts/person/`

**Comment by daniel-tabarcea** [comment]
values for this one should be something like Consultant, unv international, etc.  @drzackyll  Can you find out if this sort of data is in some un database we should sync with?
