### ISSUE TITLE
Endpoint for impacted UN personnel

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#93]
We need an endpoint to which a user can submit data related to UN impacted personnel 

The data should contain the following:
 - incident_id: numerical id  
 - agency: numerical id 
 - first_name: string
 - last_name: string
 - date_of_birth: date
 - gender: string
 - nationality: numerical id, static data needed
 - email: string
 - category: numerical id, static data needed 
 - country: numerical id 
 - job title: string
 - index_number: number 
 - status: string
 - impact_type: numerical id 
 - description: string 
 - capture_date: date
 - release_date: date
 - submitted_by: numerical id 
 - last_modified_by: numerical id 
 - last_modified_date: date
 - submitted_date: date

mandatory fields should be employer, first_name, last_name, nationality, category, country, city, status, impact_type and incident_id

Ticket for nationalities endpoint is #91
Ticket for personnel categories is #92

**Comment by daniel-tabarcea** [comment]
![screenshot from 2018-09-06 18 05 47](https://user-images.githubusercontent.com/17467562/45219738-95177500-b2b4-11e8-87b4-cbed67205912.png)
The screen for SSIRS

**Comment by daniel-tabarcea** [comment]
![personnel impact](https://user-images.githubusercontent.com/17467562/45219783-bed09c00-b2b4-11e8-889d-87f2d0246e81.png)
the screen from ssirs

**Comment by reinbach** [comment]
How should I determine whether data being provided is for an UN employer or not?
If provided with data for `employer` field, should that be the determination?

**Comment by daniel-tabarcea** [comment]
The employer should be an id for an agency if that helps
