### ISSUE TITLE
Endpoint for impacted non-UN personnel

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#94]
We need an endpoint to which a user can submit data related to non-UN impacted personnel

The data should contain the following:
- incident_id: numerical id 
- first_name: string
- last_name : string
- gender: string
- date_of_birth: date
- nationality: numerical id 
- address: string 
- county: numerical id 
- region: numerical id 
- city: numerical id
- email: string
- contact: string 
- impact_type: numerical id 
- description: string
- submitted_by: numerical id
- last_modified_by: numerical id
- last_modified_date: date
- submitted_date: date

mandatory fields should be first_name, last_name, impact_type and incident_id

Ticket for nationalities endpoint is #91

**Comment by daniel-tabarcea** [comment]
![non-un personnel](https://user-images.githubusercontent.com/17467562/45220027-85e4f700-b2b5-11e8-9275-5fcd4ec321ae.png)

**Comment by reinbach** [comment]
#85 has a different set of required fields in relation to person not in AD, I was assuming not a UN employer?

**Comment by daniel-tabarcea** [comment]
i looked at #85 and from what i understand person involved is primary_person in our current api and i don't think we need api changes for that, i just need to update the front-end. 
From what i recall person involved is the one which caused the incident so it can either be someone from un/unicef or just a random stranger

**Comment by reinbach** [comment]
Are you saying that there is only one person involved per incident? 

I thought that all those involved need to be recorded. So multiple people. Currently we have primary person, and then involved.

I'm looking at the bottom of page 21 of the SSIRS - 2.0 - Annex B document. I was getting the impression that there could be multiple people involved.

@drzackyll  could you please get some clarification on this, thanks.

**Comment by drzackyll** [comment]
@reinbach @daniel-tabarcea my understanding is that more than one person may be involved in an incident. i could be wrong, but if say two UNICEF cars crashed into each other, each with multiple people inside, it would be one event (accident), with two incidents (one for each car) and each incident would include all the people from its respective car. i will confirm this.

**Comment by drzackyll** [comment]
@ydababneh see above

**Comment by daniel-tabarcea** [comment]
![all the persons](https://user-images.githubusercontent.com/17467562/45364311-7e3d8f00-b5e2-11e8-83d5-07353262c9a2.png)
Ok, so i checked the screenshots from SSIRS and it seems that i'm wrong and there's more than one resposible party. I think what we have right now as a primary person would be the one which provides the details to the DSS country team
