### ISSUE TITLE
Endpoint for evacuation impact

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#95]
We need an endpoint to which a user can submit data related to an evacuation

The data from the form will contain the following:

- incident_id: numerical id 
- agency: numerical id 
- date: date  
- impact_type: numerical id 
- description: string
- number_international: number
- number_international_dependants: number
- number_national: number
- number_national_dependants: number
- from_country: numerical id 
- from_city: numerical id 
- to_country: numerical id 
- to_city: numerical id 
- submitted_by: numerical id
- last_modified_by: numerical id
- last_modified_date: date
- submitted_date: date

mandatory fields should be agency, impact_type and incident_id

**Comment by daniel-tabarcea** [comment]
![evacuation](https://user-images.githubusercontent.com/17467562/45220060-a1500200-b2b5-11e8-9cc7-8ffcd92e608a.png)

**Comment by reinbach** [comment]
End point;
`/api/incident_evacuations/`

editable fields;

```
{
            "incident_id",
            "impact",
            "agency",
            "date",
            "number_international",
            "number_international_dependants",
            "number_national",
            "number_national_dependants",
            "from_country",
            "from_city",
            "to_country",
            "to_city",
            "description",
}
```

evacuation impact options available at;
/api/impacts/evacuation/

**Comment by reinbach** [comment]
@drzackyll can we get a full list of the current evacuation impact types? I did not see this in the `ANNEX B - IV` document

**Comment by drzackyll** [comment]
@reinbach i believe for this the two options would be "Evacuated" and "Relocated". will confirm for you.

**Comment by reinbach** [comment]
@drzackyll thanks. I've updated with those for now, just let me know if there are more.
