### ISSUE TITLE
Endpoint for property types static data

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#96]
We need an endpoint for property types as used in the incidents impact on the property form.
Each item should have an id and a name

**Comment by reinbach** [comment]
This is available at `/api/impacts/property/`

**Comment by daniel-tabarcea** [comment]
That is for impact types, this is different. This should return something like Cash, Buildings, Vehicles, and i can't remember exactly which others. I'll update with more info if i get access to ssirs again.

**Comment by reinbach** [comment]
Ah ok

**Comment by reinbach** [comment]
endpoint available at `/api/property_types`
