### ISSUE TITLE
Endpoint for impacted property

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#97]
We need an endpoint to which a user can submit data related to an impacted property

The data should contain the following:

- incident_id: numerical id 
- agency: numerical id 
- impact_type: numerical id 
- description: string
- property_type: numerical id
- value: floating point number 
- submitted_by: numerical id
- last_modified_by: numerical id
- last_modified_date: date
- submitted_date: date

mandatory fields should be agency, impact_type, property_type and incident_id

Ticket for property types endpoint is #96

**Comment by daniel-tabarcea** [comment]
![property](https://user-images.githubusercontent.com/17467562/45220100-c6dd0b80-b2b5-11e8-90e0-7750b1440836.png)
the only screenshot i took unfortunately, no additional details on what the property types should be

**Comment by reinbach** [comment]
endpoints is at;
`/api/incident_properties/`

editable fields;

```
{
            "incident_id",
            "agency",
            "impact",
            "property_type",
            "description",
            "value",
}
```
