### ISSUE TITLE
Endpoint for impacted premise

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/sir-releases#98]
We need an endpoint to which a user can submit data related to an impacted premise

The data should contain the following:
- incident_id: numerical id 
- agency: numerical id 
- impact_type: numerical id 
- description: string
- country: numerical id 
- city: numerical id 
- un_location: numerical id, needs static data 
- premises_type: numerical id, needs static data  
- submitted_by: numerical id
- last_modified_by: numerical id
- last_modified_date: date
- submitted_date: date

mandatory fields should be agency, impact_type, premises_type and incident_id

**Comment by daniel-tabarcea** [comment]
![premises](https://user-images.githubusercontent.com/17467562/45220173-f724aa00-b2b5-11e8-88f7-8060fbd3c545.png)

**Comment by daniel-tabarcea** [comment]
Ticket for un locations endpoint is #99 
Ticket for premisses types is #100

**Comment by reinbach** [comment]
Endpoint is;
`/api/incident_premises/`

editable fields;
```
{
            "incident_id",
            "agency",
            "impact",
            "description",
            "premise_type",
            "country",
            "city",
            "un_location",
}
```
